/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DTO.BenhNhan;
import java.awt.event.MouseEvent;
import BUS.BenhNhanService;
import BUS.PhieuKhamBenhService;
import DAO.BenhNhanDAO;
import DAO.NhanVienDAO;
import DAO.PhongKhamDAO;
import DTO.NhanVien;
import DTO.PhieuKhamBenh;
import DTO.PhongKham;
import java.util.ArrayList;

import DTO.ToaThuoc;
import BUS.ToaThuocService;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author phamngochoang
 */
public class CTBenhNhanGUI extends javax.swing.JFrame {
    
    DefaultTableModel defaultTableModel;
    
    PhieuKhamBenh phieuKhamBenh;
    PhieuKhamBenhService phieuKhamBenhService;
    
    BenhNhan benhNhan;
    BenhNhanService benhNhanService;
    
    ToaThuoc toaThuoc;
    ToaThuocService toaThuocService;
    
    /**
     * Creates new form CTBenhNhanGUI
     * @param benhNhan
     */
    
    private void setTableThongTinBN(BenhNhan benhNhan){       
        defaultTableModel.addRow(new Object[]{benhNhan.getMaBN(), benhNhan.getTenBN(), benhNhan.getSdt(), benhNhan.getNgaySinh(), benhNhan.getDiaChi(), benhNhan.getQueQuan(), benhNhan.getGioiTinh(), benhNhan.getGhiChu()});
    }
    
    private void setTableData(ArrayList<PhieuKhamBenh> phieuKhamBenhs){
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        BenhNhanDAO benhNhanDAO = new BenhNhanDAO();
        PhongKhamDAO phongKhamDAO = new PhongKhamDAO();
        for (PhieuKhamBenh phieuKhamBenh : phieuKhamBenhs){           
            NhanVien nhanVien = nhanVienDAO.timNVbyID(phieuKhamBenh.getMABS());
            BenhNhan benhNhan = benhNhanDAO.timBNbyID(phieuKhamBenh.getMABN());
            PhongKham phongKham = phongKhamDAO.timPKbyID(phieuKhamBenh.getMAPK());
            defaultTableModel.addRow(new Object[]{phieuKhamBenh.getId(), phieuKhamBenh.getMAPKB(), nhanVien.getMANV(), benhNhan.getMaBN(), phongKham.getMaPK(),phieuKhamBenh.getNGAYTAO(), phieuKhamBenh.getCHANDOAN()});
        }
    }
    
    private void setTableToaThuocData(ArrayList<ToaThuoc> toaThuocs){
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        BenhNhanDAO benhNhanDAO = new BenhNhanDAO();
        PhongKhamDAO phongKhamDAO = new PhongKhamDAO();
        for (ToaThuoc toaThuoc : toaThuocs){           
            NhanVien nhanVien = nhanVienDAO.getById(toaThuoc.getMaBS());
            BenhNhan benhNhan = benhNhanDAO.getById(toaThuoc.getMaBN());
//            PhongKham phongKham = phongKhamDAO.timPKbyID(phieuKhamBenh.getMAPK());
            defaultTableModel.addRow(new Object[]{toaThuoc.getId(), toaThuoc.getMaToa(), nhanVien.getMANV(), benhNhan.getMaBN(), toaThuoc.getTongTien(), toaThuoc.getNgayLap()});
        }
    }
    
    public CTBenhNhanGUI(BenhNhan benhNhan) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.benhNhan = benhNhan;
        
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }           
        };
        
        
        
        String[] columns = {"MaBN", "Họ Tên", "Số điện thoại", "Ngày sinh", "Địa chỉ", "Quê quán", "Giới Tính", "Ghi chú"};
        defaultTableModel.setColumnIdentifiers(columns);
        
        thongTinTable.setModel(defaultTableModel);
               
        setTableThongTinBN(this.benhNhan);
        
//        ----
        
        phieuKhamBenhService = new PhieuKhamBenhService();
        
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }           
        };
        
        String[] PKBcolumns = {"Id", "MaPKB", "MaBS", "MaBN", "MaPK","Ngày Tạo", "Chẩn đoán"};
        defaultTableModel.setColumnIdentifiers(PKBcolumns);
        
        Table.setModel(defaultTableModel);
        
        int benhNhanID = this.benhNhan.getId();      

        setTableData(phieuKhamBenhService.getPhieuKhamBenhByBnID(benhNhanID));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        hienThiPKBItem = new javax.swing.JMenuItem();
        exitBt = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        thongTinTable = new javax.swing.JTable();

        hienThiPKBItem.setText("Hiện thị chi tiết Phiếu Khám Bệnh");
        hienThiPKBItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienThiPKBItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(hienThiPKBItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconTrangchu.png"))); // NOI18N
        exitBt.setText("Thoát");
        exitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtActionPerformed(evt);
            }
        });

        TitleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(0, 51, 204));
        TitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICon/iconPatient.png"))); // NOI18N
        TitleLabel.setText("THÔNG TIN BỆNH NHÂN");
        TitleLabel.setToolTipText("");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        thongTinTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        thongTinTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(thongTinTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TitleLabel)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBt)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        jPopupMenu1.show(Table, evt.getX(), evt.getY());

        if (evt.getButton() == MouseEvent.BUTTON3) {
            // Get the row index where the mouse was clicked
            int rowIndex = Table.rowAtPoint(evt.getPoint());
            // If a row is clicked
            if (rowIndex >= 0) {
                // Select the row
                Table.setRowSelectionInterval(rowIndex, rowIndex);
                // Show the popup menu at the clicked position
                jPopupMenu1.show(Table, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_TableMouseClicked

    private void hienThiPKBItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienThiPKBItemActionPerformed
        // TODO add your handling code here:
        int row = Table.getSelectedRow();
        int id = Integer.parseInt(String.valueOf(Table.getValueAt(row, 0)));
//        PhieuKhamBenh phieuKhamBenh = phieuKhamBenhService.getPhieuKhamBenhByID(id);
        new ChiTietPkbGUI(id).setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton exitBt;
    private javax.swing.JMenuItem hienThiPKBItem;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable thongTinTable;
    // End of variables declaration//GEN-END:variables
}
